image: maven:3.9.9-eclipse-temurin-17

stages:
  - test
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

test:
  stage: test
  script:
    - mvn -B test -Dspring.profiles.active=h2

package:
  stage: package
  script:
    - mvn -B clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 7 days
